### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PurvaChiniya**

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@PurvaChiniya again follow the naming conventions. Please!
The subsections should not be 5.4 or 5.4.2 or something. Only the name will suffice.
See other notebooks for reference like [this](https://github.com/dsgiitr/d2l-pytorch/blob/master/Ch4_Multilayer_Perceptrons/Dropout.ipynb)

**Comment by AnirudhDagar** [comment]
Before making a PR you need to run the notebook in order by clicking the Restart Kernel and Run All option in Jupyter.

**Comment by Prabhat-IIT** [comment]
@PurvaChiniya  please follow the guidelines of numbering subsections. Also, in `Parameter management/Custom Initialization` section I think rather than using two nested loops just to zero out some elements b/w -5 and 5 we can do subtly like this
 `a[(a>-5)&(a<5)]=0` 
> here 'a' is just a sample tensor

**Comment by PurvaChiniya** [comment]
add files via upload

**Pull request closed without merging**
