### PR TITLE
Section 10.2 and 10.3

### PR DESCRIPTION
**Pull request by vipul2001**

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@vipul2001 There are a few issues with rendering like (w1;w2; . . . ;wT ) is  bold somehow and in the line `Here the coefficients...` the latter part is being rendered in the subscript.
@saswatpp Please suggest all other the changes required.

**Comment by saswatpp** [comment]
Code is perfect. Just Copy the markdown for the 'Language Model' notebook from the actual notebook coz there are some formulae and formatting missing.

**Comment by saswatpp** [comment]
Use LaTeX Mathematical notations in the markdown as given in the actual notebook (https://en.d2l.ai/d2l-en.zip) rather than embedding its screenshot image (??)

**Comment by AnirudhDagar** [comment]
@saswatpp suggest the changes. @vipul2001 I can see that the second notebook is not rendered correctly.

**Pull request merged**
