### PR TITLE
Section-12.9_Adadelta

### PR DESCRIPTION
**Pull request by akshitmittal1**

### CODE REVIEW

**Comment by harshalmittal4** [comment]
@akshitmittal1, notebook run karna baaki hai kya?

**Comment by akshitmittal1** [comment]
@harshalmittal4 I have run the notebook in my local. It works fine. I just restarted it and cleared all the outputs

**Comment by AnirudhDagar** [comment]
@akshitmittal1 Why did you clear the outputs? We need those right!

**Comment by akshitmittal1** [comment]
@AnirudhDagar Last time you asked me to clear outputs, that's why i did it. Shall i add the outputs?

**Comment by harshalmittal4** [comment]
Add the outputs, I think , @AnirudhDagar ?

**Comment by AnirudhDagar** [comment]
Yes! Please go ahead @akshitmittal1 @harshalmittal4

**Pull request closed without merging**
