### PR TITLE
Section 5.3

### PR DESCRIPTION
**Pull request by vipul2001**

### CODE REVIEW

**Comment by vipul2001** [comment]
Done the requested changes

**Comment by saswatpp** [comment]
Replace torch.nn.init.xavier_uniform(tensor, gain=1.0) in favour of torch.nn.init.xavier_uniform_(tensor, gain=1.0) as the former is deprecated

**Comment by vipul2001** [comment]
Done the requested changes

**Comment by AnirudhDagar** [comment]
@vipul2001 Make these changes please before I can merge.
1. imports should be made in a different block (i.e. the first block) and then start with your nn.Seq...in the next notebook code block
2. Also no need to add \t(tab spaces) in print statements. Let them be without \t.
3. In the section Deferred Initialization in Practice, you have used the following method. Please follow simple and easy to read syntax in python. There can be a thousand things to achieve the same thing.
But one should follow the easy to write easy to read way.
```
def init_weights(m):
    print("Init",m.__class__.__name__)
    m
```
So make this change and try to keep this in sync with what happens in the original notebook.

I know these are very small things but we have to follow them to keep the practices same across all the notebooks.
Thanks! Let's get these changes in place by tonight.

**Comment by vipul2001** [comment]
Done changes

**Comment by AnirudhDagar** [comment]
Thanks, Great work 👍

**Comment by StevenJokes** [comment]
Why doesn't http://d2l.ai/chapter_deep-learning-computation/deferred-init.html still  PyTorch version?

**Comment by AnirudhDagar** [comment]
@StevenJokes  PyTorch doesn't provide deferred initialization.

**Pull request merged**
