### PR TITLE
add considering_the_environment

### PR DESCRIPTION
**Pull request by kanishk27DH**
add section 4.9 considering the environment

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@rsinghal757 Please look into this.

**Comment by AnirudhDagar** [comment]
Still not resolved @kanishk27DH

**Comment by AnirudhDagar** [comment]
```
$$
\mathop{\mathrm{minimize}}_w \frac{1}{n} \sum_{i=1}^n l(x_i, y_i, f(x_i)) + \mathrm{some~penalty}(w)
$$
```
@kanishk27DH This doesn't work, i mean put this in markdow?
Why use a code block?

**Comment by kanishk27DH** [comment]
ok sir I will put it in markdown but the \mathop thing is not working so I have to remove it

**Comment by AnirudhDagar** [comment]
Try this once! If it still has rendering issues..we'll use this approach.

**Comment by kanishk27DH** [comment]
@AnirudhDagar I have to drop \mathop as it is not working

**Pull request merged**
